services:
  - type: web
    name: playto-kyc-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://playto-kyc-backend.onrender.com
