# Generated by Django 5.2 on 2026-04-27 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
